// Merges answers exported from the dashboard into bob-review/answers.json and regenerates answers.md.
// Usage: node bob-review/import-answers.mjs <export.json>
// <export.json> may also be a folder written by ArtifactData `out_dir` (answers/*.json, meta/approval.json, meta/general.json).
// Export shape: { answers: {"Q-01": {status,text,fields,notes,flag,updatedAt}}, approval, general }
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { resolve } from "node:path";
const dir = process.env.BOB_REVIEW_DIR ? resolve(process.env.BOB_REVIEW_DIR) + "/" : new URL(".", import.meta.url).pathname;
const src = process.argv[2];
if (!src) { console.error("usage: node bob-review/import-answers.mjs <export.json>"); process.exit(1); }
const readJson = (f) => JSON.parse(readFileSync(f, "utf8"));
let incoming;
if (statSync(src).isDirectory()) {
  incoming = { answers: {} };
  const ad = resolve(src, "answers");
  if (existsSync(ad)) for (const f of readdirSync(ad).filter((x) => x.endsWith(".json"))) incoming.answers[f.slice(0, -5)] = readJson(resolve(ad, f));
  if (existsSync(resolve(src, "meta/approval.json"))) incoming.approval = readJson(resolve(src, "meta/approval.json"));
  if (existsSync(resolve(src, "meta/general.json"))) incoming.general = readJson(resolve(src, "meta/general.json")).notes || "";
} else incoming = readJson(src);
const questions = JSON.parse(readFileSync(dir + "questions.json", "utf8"));
const path = dir + "answers.json";
const store = existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : { answers: {}, approval: null, general: "" };
const now = new Date().toISOString();
let changed = 0;
for (const [id, a] of Object.entries(incoming.answers || {})) {
  const prev = store.answers[id];
  const same = prev && ["status", "text", "notes", "flag"].every((k) => (prev[k] || "") === (a[k] || "")) && JSON.stringify(prev.fields || {}) === JSON.stringify(a.fields || {});
  if (!same) { store.answers[id] = { ...a, importedAt: now }; changed++; }
}
if (incoming.approval) store.approval = incoming.approval;
if (typeof incoming.general === "string") store.general = incoming.general;
store.lastImport = now;
writeFileSync(path, JSON.stringify(store, null, 2) + "\n");

const label = { answered: "Answered", open: "Open", discuss: "Discuss with Miah", later: "Come back later" };
const lines = [`# Bob's answers: three-role strategy v${questions.version}`, "", `Imported ${now} from the dashboard. Source of truth: \`answers.json\`. Regenerated by \`import-answers.mjs\`; do not edit by hand.`, ""];
if (store.approval) {
  const a = store.approval, d = { approve: "Approve as written", "approve-changes": "Approve with changes", hold: "Hold" }[a.decision] || a.decision;
  lines.push("## Decision", "", `- **${d}**, signed ${a.signedName || "(no name)"} on ${a.date || "(no date)"}, recorded ${a.recordedAt}.`);
  if (a.conditions) lines.push(`- Conditions: ${a.conditions}`);
  lines.push("");
} else lines.push("## Decision", "", "- Not recorded yet.", "");
for (const sec of questions.sections) {
  lines.push(`## ${sec.title}`, "");
  for (const q of sec.questions) {
    const a = store.answers[q.id];
    lines.push(`### ${q.id} ${q.title}`, "", `*${q.prompt}*`, "");
    if (!a) { lines.push("- Status: Open (no answer imported)", ""); continue; }
    lines.push(`- Status: ${label[a.status] || a.status}`);
    for (const f of q.fields || []) if ((a.fields || {})[f.key]) lines.push(`- ${f.label}: ${a.fields[f.key]}`);
    if (a.text) lines.push(`- Answer: ${a.text.replace(/\n/g, "\n  ")}`);
    if (a.notes) lines.push(`- Additional information: ${a.notes.replace(/\n/g, "\n  ")}`);
    lines.push("");
  }
}
if (store.general) lines.push("## Anything else", "", store.general, "");
writeFileSync(dir + "answers.md", lines.join("\n"));
const answered = Object.values(store.answers).filter((a) => a.status === "answered").length;
console.log(`imported: ${changed} changed, ${answered} answered of ${questions.sections.flatMap((s) => s.questions).length}`);
